Repository codeamp/circuit, pull requests merged in 2018-09, with the labels that each got.

#326 Fix CircleCI
  .circleci/config.yml
  .gitignore
  plugins/codeamp/migrations.go
  plugins/route53/route53.go
Labels: P/High, S/Review

#325 Make project query environment param optional
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/project_query.go
  plugins/codeamp/graphql/project_test.go
Labels: P/Medium

#329 Add service.Name validation so cannot be longer than 63 chars
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/service_test.go
Labels: P/Low, S/Review, T/Enhancement

#328 Fixed Features Ordering Issue
  plugins/codeamp/db/paginator.go
  plugins/codeamp/db/project.go
Labels: P/Medium, S/Review, T/Bug

#331 Fixed issue with features page displaying all features
  plugins/codeamp/db/project.go
Labels: P/Medium, T/Bug
