Repository codeamp/circuit, pull requests merged in 2018-10, with the labels that each got.

#342 CreateRelease Creates Release if it is not Eligible
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/release_test.go
Labels: P/Medium, T/Bug

#348 Mutation.go Organization
  plugins/codeamp/graphql/environment_mutation.go
  plugins/codeamp/graphql/extension_mutation.go
  plugins/codeamp/graphql/helpers.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/project_mutation.go
  plugins/codeamp/graphql/project_query.go
  plugins/codeamp/graphql/projectextension_mutation.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/secret_mutation.go
  plugins/codeamp/graphql/service_mutation.go
  plugins/codeamp/graphql/service_test.go
  plugins/codeamp/graphql/servicespec_mutation.go
  plugins/codeamp/graphql/user_mutation.go
  plugins/codeamp/graphql/user_test.go
Labels: P/Medium, S/Review, T/Maintenance

#349 Mocked Heartbeat test as a test case for future mocking
  plugins/heartbeat/heartbeat.go
  plugins/heartbeat/heartbeat_test.go
  plugins/heartbeat/interfaces.go
  plugins/heartbeat/interfaces_test.go
Labels: P/Low, S/Review, T/Enhancement

#350 DockerBuilder Test Mocking
  plugins/dockerbuilder/dockerbuilder.go
  plugins/dockerbuilder/dockerbuilder_test.go
  plugins/dockerbuilder/interfaces.go
  plugins/dockerbuilder/interfaces_test.go
Labels: P/Medium, S/Review, T/Enhancement

#355 Mutation Organization Continued
  plugins/codeamp/graphql/helpers.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/release_mutation.go
Labels: P/Low, S/Review, T/Enhancement

#345 patch: fix caching by getting consistent service signatures and add cacheable property
  assets/assets.go
  plugins/codeamp/graphql/extension.go
  plugins/codeamp/graphql/extension_mutation.go
  plugins/codeamp/graphql/extension_test.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/migrations.go
  plugins/codeamp/model/input.go
  plugins/codeamp/model/model.go
  plugins/codeamp/release_handler.go
Labels: P/High, S/Review

#356 Slack Prettified
  plugins/slack/slack.go
  vendor/github.com/lytics/slackhook/slackhook.go
Labels: P/Low, S/Review, T/Enhancement

#358 Update ELB Log location
  plugins/kubernetes/loadbalancer.go
Labels: P/Medium, S/Review
