Repository codeamp/circuit, pull requests merged in 2018-07, with the labels that each got.

#266 fix: send Deployment level extension events even if a user is not found
  plugins/codeamp/gitsync_handler.go
  plugins/codeamp/workflowreleaseextension_handler.go
Labels: P/Critical, S/Review

#245 Add pagination for Projects, Releases, Services, Features and Secrets
  assets/assets.go
  plugins/codeamp/db/feature.go
  plugins/codeamp/db/paginator.go
  plugins/codeamp/db/project.go
  plugins/codeamp/db/release.go
  plugins/codeamp/graphql/environment_test.go
  plugins/codeamp/graphql/feature_query.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/paginator.go
  plugins/codeamp/graphql/project.go
  plugins/codeamp/graphql/project_query.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/query.go
  plugins/codeamp/graphql/release_query.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/graphql/secret_query.go
  plugins/codeamp/graphql/service_query.go
  plugins/codeamp/model/input.go
  vendor/vendor.json
Labels: S/Completed

#252 Resolvers Test Coverage
  .circleci/config.yml
  README.md
  plugins/codeamp/auth/auth.go
  plugins/codeamp/codeamp.go
  plugins/codeamp/db/project.go
  plugins/codeamp/db/release.go
  plugins/codeamp/db/service.go
  plugins/codeamp/graphql/environment_test.go
  plugins/codeamp/graphql/extension_test.go
  plugins/codeamp/graphql/feature_query.go
  plugins/codeamp/graphql/feature_test.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/json_test.go
  plugins/codeamp/graphql/middleware.go
  plugins/codeamp/graphql/middleware_test.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/permission_query.go
  plugins/codeamp/graphql/project.go
  plugins/codeamp/graphql/project_query.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/projectextension_test.go
  plugins/codeamp/graphql/query.go
  plugins/codeamp/graphql/release_query.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/releaseextension_test.go
  plugins/codeamp/graphql/resolver.go
  plugins/codeamp/graphql/resolver_test.go
  plugins/codeamp/graphql/secret.go
  plugins/codeamp/graphql/secret_query.go
  plugins/codeamp/graphql/secret_test.go
  plugins/codeamp/graphql/service_query.go
  plugins/codeamp/graphql/service_test.go
  plugins/codeamp/graphql/servicespec_test.go
  plugins/codeamp/graphql/user_query.go
  plugins/codeamp/graphql/user_test.go
  plugins/codeamp/model/model.go
  plugins/dockerbuilder/dockerbuilder_test.go
  test/test.go
Labels: P/Medium, S/Review

#279 Provision default envs for project on creation and remove envID param
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/mutation.go
Labels: P/Medium, S/Review, T/Bug

#264 Mutation Tests
  .circleci/config.yml
  plugins/codeamp/graphql/environment_test.go
  plugins/codeamp/graphql/feature_test.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/projectextension_test.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/releaseextension_test.go
  plugins/codeamp/graphql/secret_test.go
  plugins/codeamp/graphql/service_test.go
  plugins/dockerbuilder/dockerbuilder_test.go
Labels: S/Review

#280 fix: fix pagination logic to be consistent among all resolvers
  plugins/codeamp/db/paginator.go
  plugins/codeamp/db/project.go
Labels: P/High, S/Review, T/Bug

#286 Test Coverage
  plugins/codeamp/graphql/environment_test.go
  plugins/codeamp/graphql/extension_test.go
  plugins/codeamp/graphql/helpers.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/project.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/projectextension_test.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/service_test.go
  plugins/codeamp/graphql/servicespec_test.go
  plugins/codeamp/graphql/user_test.go
Labels: P/Medium, S/Review

#295 Update transistor package
  vendor/github.com/codeamp/transistor/event.go
  vendor/github.com/codeamp/transistor/utils.go
  vendor/vendor.json
Labels: P/Critical, T/Bug

#296 Authentication
  plugins/codeamp/auth/auth.go
  plugins/codeamp/auth/auth_test.go
  plugins/codeamp/graphql/user_query.go
  test/test.go
Labels: P/High, S/Completed, T/Bug

#292 Test Coverage: Pt 3
  plugins/codeamp/graphql/environment_test.go
  plugins/codeamp/graphql/extension_test.go
  plugins/codeamp/graphql/feature_test.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/projectextension_test.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/releaseextension_test.go
  plugins/codeamp/graphql/secret_test.go
  plugins/codeamp/graphql/service_test.go
  plugins/codeamp/graphql/servicespec_test.go
  plugins/codeamp/graphql/user_test.go
  test/test.go
Labels: S/Review

#293 Project Resolver: Return all associated releases
  plugins/codeamp/db/project.go
Labels: P/Medium, S/Review

#298 Test Coverage: Pt 4
  plugins/codeamp/auth/auth_test.go
  plugins/codeamp/graphql/middleware_test.go
  plugins/codeamp/graphql/paginator_test.go
  plugins/codeamp/graphql/release_test.go
Labels: P/Medium, S/Review

#304 Change containerPort type assertion to reflect type change from string to int
  plugins/kubernetes/loadbalancer.go
Labels: P/Critical, T/Bug

#305 Fixes Secret's Versions Timestamps
  plugins/codeamp/graphql/secret.go
Labels: S/Review, T/Bug

#306 Preserve Release Extension History
  plugins/codeamp/graphql/mutation.go
Labels: S/Review, T/Bug

#303 Headers for health probes
  assets/assets.go
  plugins/codeamp/db/service.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/graphql/service_test.go
  plugins/codeamp/migrations.go
  plugins/codeamp/model/input.go
  plugins/codeamp/model/model.go
  plugins/events.go
  plugins/kubernetes/deployment.go
Labels: S/Review

#308 correctly add http headers to release events
  plugins/codeamp/graphql/helpers.go
  plugins/codeamp/graphql/release_test.go
Labels: S/Review

#300 Change deployment strategy on rollbacks
  assets/assets.go
  plugins/codeamp/graphql/helpers.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/release.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/releaseextension_test.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/model/model.go
  plugins/codeamp/workflowreleaseextension_handler.go
  plugins/events.go
  plugins/kubernetes/deployment.go
Labels: P/High, S/Review, T/Enhancement

#310 Send Websockets msg to Releases page on CD
  plugins/codeamp/gitsync_handler.go
Labels: P/Low, S/Review, T/Enhancement
