Repository codeamp/circuit, pull requests merged in 2018-12, with the labels that each got.

#388 Fix Slack Notification Footer
  plugins/slack/slack.go
Labels: P/Medium, T/Bug

#391 Pin Golang Base Docker Image
  Dockerfile
Labels: P/High, T/Bug

#376 Errors Interface + KubeConfig overhaul
  plugins/kubernetes/deployment.go
  plugins/kubernetes/deployment_test.go
  plugins/kubernetes/errors.go
  plugins/kubernetes/interfaces.go
  plugins/kubernetes/interfaces_test.go
  plugins/kubernetes/kubernetes.go
  plugins/kubernetes/loadbalancer.go
  plugins/kubernetes/services_test.go
  plugins/kubernetes/types.go
  vendor/github.com/go-errors/errors/.travis.yml
  vendor/github.com/go-errors/errors/LICENSE.MIT
  vendor/github.com/go-errors/errors/README.md
  vendor/github.com/go-errors/errors/error.go
  vendor/github.com/go-errors/errors/parse_panic.go
  vendor/github.com/go-errors/errors/stackframe.go
Labels: P/Medium, S/Review, T/Enhancement

#395 remove admin requirement from SecretQueryResolver
  plugins/codeamp/graphql/secret_query.go
Labels: S/Review

#390 Slack Notifications for Automated Releases
  plugins/codeamp/codeamp.go
  plugins/codeamp/gitsync_handler.go
  plugins/codeamp/migrations.go
  plugins/codeamp/workflowreleaseextension_handler.go
  plugins/gitsync/gitsync.go
  plugins/slack/slack.go
Labels: P/Low, S/Review, T/Bug

#396 Don't reference variable before error checking occurs
  plugins/kubernetes/loadbalancer.go
Labels: P/High, S/Review, T/Bug

#397 Release Touchups
  plugins/codeamp/graphql/release_mutation.go
  plugins/codeamp/graphql/releaseextension_test.go
  plugins/codeamp/graphql/servicespec_query.go
  plugins/codeamp/release_handler.go
Labels: P/Low, T/Bug
