Repository codeamp/circuit, pull requests merged in 2018-11, with the labels that each got.

#360 Fix route53 extensions same-subdomain prevention
  plugins/codeamp/graphql/projectextension_mutation.go
Labels: P/High, S/Review

#361 Test to prevent duplicated Route53 entries
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/projectextension_mutation.go
  plugins/codeamp/graphql/projectextension_test.go
Labels: P/High, S/Review, T/Bug

#353 Kubernetes Tests
  plugins/kubernetes/deployment.go
  plugins/kubernetes/deployment_test.go
  plugins/kubernetes/ingress.go
  plugins/kubernetes/ingress_route.go
  plugins/kubernetes/interfaces.go
  plugins/kubernetes/interfaces_test.go
  plugins/kubernetes/kubernetes.go
  plugins/kubernetes/kubernetes_test.go
  plugins/kubernetes/loadbalancer.go
  plugins/kubernetes/services_test.go
  plugins/kubernetes/testdata/kubeconfig
  plugins/kubernetes/types.go
Labels: P/High, S/Review

#370 Fixes Extension Query Improper Where Clause
  plugins/codeamp/graphql/extension_query.go
Labels: P/Medium, S/Review, T/Bug

#373 Test Improvements & General Housekeeping
  plugins/codeamp/auth/auth.go
  plugins/codeamp/gitsync_handler.go
  plugins/dockerbuilder/dockerbuilder_test.go
  plugins/dockerbuilder/interfaces.go
  plugins/dockerbuilder/interfaces_test.go
  plugins/heartbeat/heartbeat_test.go
  plugins/slack/slack_test.go
Labels: P/Medium, S/Review

#372 Kubernetes Tests
  plugins/kubernetes/deployment.go
  plugins/kubernetes/deployment_test.go
  plugins/kubernetes/ingress.go
  plugins/kubernetes/ingress_route.go
  plugins/kubernetes/interfaces.go
  plugins/kubernetes/interfaces_test.go
  plugins/kubernetes/kubernetes.go
  plugins/kubernetes/kubernetes_test.go
  plugins/kubernetes/loadbalancer.go
  plugins/kubernetes/services_test.go
  plugins/kubernetes/testdata/kubeconfig
  plugins/kubernetes/types.go
Labels: P/Medium, S/Review

#378 Delete old bookmarks
  plugins/codeamp/graphql/project_mutation.go
Labels: P/Low, S/Review, T/Bug

#368 Disable servicespec selection on service creation
  assets/assets.go
  plugins/codeamp/db/service.go
  plugins/codeamp/db/servicespec.go
  plugins/codeamp/graphql/environment_test.go
  plugins/codeamp/graphql/helpers_test.go
  plugins/codeamp/graphql/paginator_test.go
  plugins/codeamp/graphql/project_mutation.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/release_mutation.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/graphql/service_mutation.go
  plugins/codeamp/graphql/service_test.go
  plugins/codeamp/graphql/servicespec.go
  plugins/codeamp/graphql/servicespec_mutation.go
  plugins/codeamp/graphql/servicespec_test.go
  plugins/codeamp/migrations.go
  plugins/codeamp/model/input.go
Labels: S/Review
