Repository codeamp/circuit, pull requests merged in 2018-06, with the labels that each got.

#248 create POD_IP env var from status metadata
  plugins/kubernetes/deployment.go
Labels: (╯°□°）╯︵ ┻━┻, S/Completed, T/Enhancement

#261 fix: rm 'create' events for releaseExtension in StopRelease
  plugins/codeamp/graphql/mutation.go
Labels: P/High, S/Review, T/Bug

#262 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: S/Review

#263 Add pr template
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
Labels: S/Review
