Repository codeamp/circuit, pull requests merged in 2019-04, with the labels that each got.

#447 Private Loadbalancers Whitelist
  plugins/kubernetes/loadbalancer.go
  plugins/kubernetes/services_test.go
Labels: P/Medium, S/Review

#448 Allow Project Extension to Append Whitelist Rules for ELB
  plugins/kubernetes/loadbalancer.go
Labels: P/High, S/Review

#449 Updated CircleCI: Only report test results if tokens are set
  .circleci/config.yml
Labels: P/Medium, S/Review

#452 KongIngress Cluster IP Fix
  plugins/kubernetes/ingress_kong.go
Labels: S/Review, T/Bug

#451 Fix: add unique ids in postgresql database plugin and response event structure
  main.go
  plugins/database/database.go
  plugins/database/database_test.go
  plugins/database/helpers.go
  plugins/database/postgresql.go
Labels: S/Review

#454 S3 Self Service Plugin
  configs/circuit.yml
  main.go
  plugins/codeamp/projectextension_handler.go
  plugins/events.go
  plugins/s3/interface.go
  plugins/s3/interface_test.go
  plugins/s3/s3.go
  plugins/s3/s3_test.go
Labels: P/High, S/Review, T/Enhancement

#456 Include SSL_MODE input artifact for database plugin
  plugins/database/database.go
  plugins/database/database_test.go
  plugins/database/helpers.go
  plugins/database/postgresql.go
Labels: S/Review

#458 Add mysql plugin
  .circleci/config.yml
  Gopkg.lock
  Gopkg.toml
  docker-compose.yml
  plugins/database/constants.go
  plugins/database/database.go
  plugins/database/database_test.go
  plugins/database/helpers.go
  plugins/database/mysql.go
  vendor/github.com/go-sql-driver/mysql/.github/ISSUE_TEMPLATE.md
  vendor/github.com/go-sql-driver/mysql/.github/PULL_REQUEST_TEMPLATE.md
  vendor/github.com/go-sql-driver/mysql/.gitignore
  vendor/github.com/go-sql-driver/mysql/.travis.yml
  vendor/github.com/go-sql-driver/mysql/.travis/docker.cnf
  vendor/github.com/go-sql-driver/mysql/.travis/gofmt.sh
  vendor/github.com/go-sql-driver/mysql/.travis/wait_mysql.sh
  vendor/github.com/go-sql-driver/mysql/AUTHORS
  vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
  vendor/github.com/go-sql-driver/mysql/CONTRIBUTING.md
  vendor/github.com/go-sql-driver/mysql/LICENSE
  vendor/github.com/go-sql-driver/mysql/README.md
  vendor/github.com/go-sql-driver/mysql/appengine.go
  vendor/github.com/go-sql-driver/mysql/auth.go
  vendor/github.com/go-sql-driver/mysql/auth_test.go
  vendor/github.com/go-sql-driver/mysql/benchmark_go18_test.go
  vendor/github.com/go-sql-driver/mysql/benchmark_test.go
  vendor/github.com/go-sql-driver/mysql/buffer.go
  vendor/github.com/go-sql-driver/mysql/collations.go
  vendor/github.com/go-sql-driver/mysql/connection.go
  vendor/github.com/go-sql-driver/mysql/connection_go18.go
  vendor/github.com/go-sql-driver/mysql/connection_go18_test.go
  vendor/github.com/go-sql-driver/mysql/connection_test.go
  vendor/github.com/go-sql-driver/mysql/const.go
  vendor/github.com/go-sql-driver/mysql/driver.go
  vendor/github.com/go-sql-driver/mysql/driver_go18_test.go
  vendor/github.com/go-sql-driver/mysql/driver_test.go
  vendor/github.com/go-sql-driver/mysql/dsn.go
  vendor/github.com/go-sql-driver/mysql/dsn_test.go
  vendor/github.com/go-sql-driver/mysql/errors.go
  vendor/github.com/go-sql-driver/mysql/errors_test.go
  vendor/github.com/go-sql-driver/mysql/fields.go
  vendor/github.com/go-sql-driver/mysql/infile.go
  vendor/github.com/go-sql-driver/mysql/packets.go
  vendor/github.com/go-sql-driver/mysql/packets_test.go
  vendor/github.com/go-sql-driver/mysql/result.go
  vendor/github.com/go-sql-driver/mysql/rows.go
  vendor/github.com/go-sql-driver/mysql/statement.go
  vendor/github.com/go-sql-driver/mysql/statement_test.go
  vendor/github.com/go-sql-driver/mysql/transaction.go
  vendor/github.com/go-sql-driver/mysql/utils.go
  vendor/github.com/go-sql-driver/mysql/utils_go17.go
  vendor/github.com/go-sql-driver/mysql/utils_go18.go
  vendor/github.com/go-sql-driver/mysql/utils_go18_test.go
  vendor/github.com/go-sql-driver/mysql/utils_test.go
Labels: P/High, S/Review
