Repository codeamp/circuit, pull requests merged in 2019-05, with the labels that each got.

#462 Patch: change genDBUser func to have 14 chars
  plugins/database/constants.go
  plugins/database/database.go
  plugins/database/helpers.go
Labels: S/Review, T/Bug

#463 Patch: convert genDBUser and genDBPass to genRandomAlphabetStringWithLength in database plugin
  plugins/database/database.go
  plugins/database/database_test.go
  plugins/database/helpers.go
Labels: S/Review, T/Bug

#465 apply kong service updates when the codeamp extension is updated
  plugins/kubernetes/ingress_kong.go
Labels: S/Review

#460 Add redis plugin
  plugins/events.go
  plugins/kubernetes/constants.go
  plugins/kubernetes/deployment_test.go
  plugins/kubernetes/interfaces.go
  plugins/kubernetes/interfaces_test.go
  plugins/kubernetes/kubernetes.go
  plugins/kubernetes/redis.go
  plugins/kubernetes/redis_test.go
  plugins/kubernetes/types.go
Labels: S/Review

#467 Mongo Self Service Plugin
  configs/circuit.yml
  main.go
  plugins/events.go
  plugins/mongo/interface.go
  plugins/mongo/interface_test.go
  plugins/mongo/models.go
  plugins/mongo/mongo.go
  plugins/mongo/mongo_test.go
  plugins/s3/interface.go
  plugins/s3/s3.go
Labels: P/High, S/Review

#472 Add postgres fix to creating usernames that can have both upper and lower case chars
  plugins/database/postgresql.go
Labels: S/Review, T/Bug

#477 S3 Plugin Creates Buckets
  plugins/s3/interface.go
  plugins/s3/interface_test.go
  plugins/s3/s3.go
  plugins/s3/s3_test.go
Labels: P/Medium, S/Review, T/Enhancement

#475 Scheduled Build Releaser
  configs/circuit.test.yml
  configs/circuit.yml
  main.go
  plugins/codeamp/codeamp.go
  plugins/codeamp/heartbeat_handler.go
  plugins/codeamp/projectextension_handler.go
  plugins/codeamp/scheduledbranchreleaser_handler.go
  plugins/codeamp/workflowreleaseextension_handler.go
  plugins/events.go
  plugins/kubernetes/deployment.go
  plugins/scheduledbranchreleaser/models.go
  plugins/scheduledbranchreleaser/scheduledbranchreleaser.go
  plugins/scheduledbranchreleaser/scheduledbranchreleaser_test.go
  test/test.go
  vendor/github.com/codeamp/transistor/transistor.go
Labels: P/Medium, S/Review, T/Feature Request
