Repository codeamp/circuit, pull requests merged in 2019-01, with the labels that each got.

#399 Migrations Report Success in Failure Condition
  plugins/codeamp/migrations.go
Labels: P/Low, S/Review, T/Bug

#400 DockerBuilder Fetches
  plugins/dockerbuilder/dockerbuilder.go
Labels: P/High, S/Review, T/Bug

#402 Project Secrets Search
  assets/assets.go
  plugins/codeamp/db/project.go
  plugins/codeamp/graphql/project.go
  plugins/codeamp/graphql/project_query.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/schema.graphql
Labels: P/High, S/Review, T/Feature Request

#404 Support Service Filtering
  assets/assets.go
  plugins/codeamp/db/project.go
  plugins/codeamp/graphql/project.go
  plugins/codeamp/graphql/project_test.go
  plugins/codeamp/graphql/schema.graphql
Labels: P/High, S/Review, T/Feature Request

#405 Add logging for Project/Settings changes
  plugins/codeamp/auth/auth.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/project_mutation.go
  plugins/codeamp/graphql/project_test.go
  test/test.go
Labels: P/Medium, S/Review, T/Enhancement

#408 Add caching fix with test case
  plugins/codeamp/graphql/release_mutation.go
  plugins/codeamp/graphql/release_test.go
  plugins/codeamp/release_handler.go
Labels: P/High

#411 Add secrets importer
  assets/assets.go
  plugins/codeamp/graphql/mutation.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/graphql/secret_mutation.go
  plugins/codeamp/graphql/secret_test.go
  plugins/codeamp/model/input.go
  plugins/codeamp/model/model.go
  plugins/events.go
Labels: S/Review
