Repository codeamp/circuit, pull requests merged in 2019-02, with the labels that each got.

#413 Add secrets exporter
  assets/assets.go
  plugins/codeamp/graphql/query.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/graphql/secret_query.go
  plugins/codeamp/graphql/secret_test.go
  plugins/codeamp/model/input.go
Labels: P/High, S/Review, T/Enhancement

#418 Unwind Failed Deploys
  plugins/kubernetes/deployment.go
  plugins/kubernetes/deployment_test.go
  plugins/kubernetes/errors.go
  plugins/kubernetes/interfaces.go
  plugins/kubernetes/interfaces_test.go
  plugins/kubernetes/kubernetes.go
  plugins/kubernetes/types.go
Labels: P/Critical, S/Review, T/Bug

#423 Fix schema.graphql errors for Import/Export related functions
  assets/assets.go
  plugins/codeamp/graphql/query.go
  plugins/codeamp/graphql/schema.graphql
  plugins/codeamp/graphql/secret_mutation.go
  plugins/codeamp/graphql/secret_test.go
Labels: S/Review, T/Bug

#426 Add 'must be general type' condition if creating ports in createService
  plugins/codeamp/graphql/service_mutation.go
  plugins/codeamp/graphql/service_test.go
Labels: S/Review, T/Bug

#428 Add "project" scope when importing secrets
  plugins/codeamp/graphql/secret_mutation.go
  plugins/codeamp/graphql/secret_test.go
Labels: T/Bug

#433 Ignore ports variable if length is 0
  plugins/codeamp/graphql/service_mutation.go
  plugins/codeamp/graphql/service_test.go
Labels: P/Critical, S/Review, T/Bug
