Repository codeamp/circuit, pull requests merged in 2019-06, with the labels that each got.

#480 kong ingress extension input handling
  plugins/kubernetes/ingress_kong.go
Labels: P/Low, S/Review, T/Bug

#482 delete kong service on extension uninstall
  plugins/kubernetes/ingress_kong.go
Labels: P/Medium, S/Review, T/Bug

#474 Add Complainer logic for notifying when features have been successfully deployed to "production" before "staging"
  configs/circuit.test.yml
  configs/circuit.yml
  plugins/codeamp/complainer.go
  plugins/codeamp/complainer_test.go
  plugins/codeamp/release_handler.go
  plugins/slack/slack.go
Labels: P/High, S/Review

#483 Kong ingress extension tests
  .circleci/config.yml
  bootstrap/postgres/init-dex-db.sh
  bootstrap/postgres/init-kong-db.sh
  docker-compose.yml
  plugins/events.go
  plugins/kubernetes/ingress.go
  plugins/kubernetes/ingress_helpers.go
  plugins/kubernetes/ingress_kong.go
  plugins/kubernetes/ingress_kong_test.go
  plugins/kubernetes/ingress_route.go
Labels: S/Review
